version: 2
updates:
  - package-ecosystem: "helm"
    directories:
      - "/"
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
    groups:
      helm-dependencies:
        patterns:
          - "*"
