{{- if .Values.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  selfSigned: {}
{{- end }}
