apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "private-ai.fullname" . }}
  labels:
    {{- include "private-ai.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "private-ai.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "private-ai.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      containers:
        - name: {{ .Chart.Name }}          
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- if or .Values.limits.enabled .Values.requests.enabled .Values.gpuEnabled }}
          resources:
            {{- if or .Values.limits.enabled .Values.gpuEnabled }}
            limits:
              {{- if .Values.gpuEnabled }}
              nvidia.com/gpu: 1
              {{- end }}
              memory: {{ .Values.limits.memory }}
              cpu: {{ .Values.limits.cpu }}
            {{- end }}
            {{- if .Values.requests.enabled}}
            requests:
              memory: {{ .Values.requests.memory }}
              cpu: {{ .Values.requests.cpu }}
            {{- end }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- with .Values.envVars }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.name }}
                optional: true
          volumeMounts:
            - name: {{ .Values.license.volumeMount }}
              mountPath: /app/license
          {{- if .Values.gpuEnabled }}
            - name: dshm-volume
              mountPath: /dev/shm
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.timeoutSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
      volumes:
        - name: {{ .Values.license.volumeMount }}
          secret:
            secretName: {{ .Values.license.name }}
      {{- if .Values.gpuEnabled }}
        - name: dshm-volume
          emptyDir:
            medium: Memory
      {{- end }}

      affinity:
        {{- if .Values.nodeAffinity.enabled}}
        {{- with .Values.nodeAffinity.values}}
        nodeAffinity:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}

        {{- if .Values.podAntiAffinity.enabled}}
        {{- with .Values.podAntiAffinity.values}}
        podAntiAffinity:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
      
      {{- if .Values.topologySpreadConstraints.enabled}}
      {{- with .Values.topologySpreadConstraints.values}}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      
      {{- if .Values.tolerations.enabled}}
      {{- with .Values.tolerations.values}}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}