{{- if not .Values.externalsecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "private-ai.labels" . | nindent 4 }}
data:
{{- range .Values.secrets.data }}
  {{ .name }}: {{ .value | b64enc }}
{{- end }}
{{- end }}
