apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "private-ai-deid.fullname" . }}
  labels:
    {{- include "private-ai-deid.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "private-ai-deid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "private-ai-deid.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}      
      containers:
        - name: {{ .Chart.Name }}          
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- if .Values.gpuEnabled }}
          resources:
            limits:
              nvidia.com/gpu: 1
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- with .Values.envVars }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if not .Values.license.isMarketplace }}
          volumeMounts:
            - name: {{ .Values.license.volumeMount }}
              mountPath: {{ .Values.license.mountPath }}
            {{- if .Values.gpuEnabled }}
            - name: dshm-volume
              mountPath: /dev/shm
            {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            periodSeconds: {{ .Values.service.periodSeconds }}
            initialDelaySeconds: {{ .Values.service.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.service.timeoutSeconds }}
      {{- if not .Values.license.isMarketplace }}              
      volumes:
        - name: {{ .Values.license.volumeMount }}
          configMap:
            name: {{ .Values.license.name }}
            items:
              - key: license.info
                path: license.json
        {{- if .Values.gpuEnabled }}
        - name: dshm-volume
          emptyDir:
            medium: Memory
        {{- end }}
      {{- end }}