{{ if ((.Values.ingress).enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "private-ai-deid.fullname" . }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "private-ai-deid.fullname" . }}
            port:
              number: {{ .Values.service.port }}
        path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.sslSecret }}
{{ end }}
