{{- if .Values.externalsecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
spec:
  externalSecretName: {{ .Values.imagePullSecrets.name }}
  {{- with .Values.externalsecrets.namespaceSelectors }}
  namespaceSelectors:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  refreshTime: {{ .Values.externalsecrets.refreshTime }}
  externalSecretSpec:
    secretStoreRef:
      name: {{ .Values.externalsecrets.clustersecretstorename }}
      kind: ClusterSecretStore
    refreshInterval: {{ .Values.externalsecrets.dockercredential.refreshInterval }}
    target:
      name: {{ .Values.imagePullSecrets.name }}
      template:
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: '{"auths":{"{{ .registryHost }}":{"username":"{{ .registryName }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .registryName .password | b64enc }}"}}}'
    data:
      - secretKey: registryHost
        remoteRef:
          key: {{ .Values.externalsecrets.dockercredential.remoteRefKey }}
          property: {{ .Values.externalsecrets.dockercredential.serverProperty }}
      - secretKey: registryName
        remoteRef:
          key: {{ .Values.externalsecrets.dockercredential.remoteRefKey }}
          property: {{ .Values.externalsecrets.dockercredential.usernameProperty }}
      - secretKey: password
        remoteRef:
          key: {{ .Values.externalsecrets.dockercredential.remoteRefKey }}
          property: {{ .Values.externalsecrets.dockercredential.passwordProperty }}
{{- end }}
