{{- if .Values.externalsecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
spec:
  secretStoreRef:
    name: {{ .Values.externalsecrets.secretstorename }}
    kind: SecretStore
  refreshInterval: {{ .Values.externalsecrets.dockercredential.refreshInterval }}
  target:
    name: {{ .Values.imagePullSecrets.name }}
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"{{ `{{ .registryHost }}` }}":{"username":"{{ `{{ .registryName }}` }}", "password":"{{ `{{ .registryPassword }}` }}", "auth": "{{ `{{ printf "%s:%s" .registryName .registryPassword | b64enc }}` }}"}}}'
  data:
    - secretKey: registryHost
      remoteRef:
        key: {{ .Values.externalsecrets.dockercredential.remoteRefKey }}
        property: {{ .Values.externalsecrets.dockercredential.serverProperty }}
    - secretKey: registryName
      remoteRef:
        key: {{ .Values.externalsecrets.dockercredential.remoteRefKey }}
        property: {{ .Values.externalsecrets.dockercredential.usernameProperty }}
    - secretKey: registryPassword
      remoteRef:
        key: {{ .Values.externalsecrets.dockercredential.remoteRefKey }}
        property: {{ .Values.externalsecrets.dockercredential.passwordProperty }}
{{- end }}
