{{- if .Values.externalsecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: {{ .Values.license.name }}
spec:
  externalSecretName: {{ .Values.license.name }}
  {{- with .Values.externalsecrets.namespaceSelectors }}
  namespaceSelectors:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  refreshTime: {{ .Values.externalsecrets.refreshTime }}
  externalSecretSpec:
    secretStoreRef:
      name: {{ .Values.externalsecrets.clustersecretstorename }}
      kind: ClusterSecretStore
    refreshInterval: {{ .Values.externalsecrets.license.refreshInterval }}
    target:
      name: {{ .Values.license.name }}
    data:
      - secretKey: license.json
        remoteRef:
          key: {{ .Values.externalsecrets.license.remoteRef }}
          property: license.json
{{- end }}
